branches:
  only:
    - master
language: node_js
node_js:
- lts/*
git:
  depth: 30
install:
- yarn --frozen-lockfile
- yarn test
script:
- ./build.sh
after_script:
- ./notify.sh
cache: yarn
deploy:
- provider: pages
  local-dir: styleguide
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
- provider: npm
  email: levy9527@qq.com
  api_key: $NPM_TOKEN
  skip-cleanup: true
